=== Tellenn/ProjetFinalL3/Modules/Calendrier/schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/projetjava"
           xmlns="http://www.ujf-grenoble.fr/l3miage/projetjava"
           elementFormDefault="qualified">
    
    <xs:element name="calendrier" type="Calendrier"/>
    <xs:complexType name="Calendrier">
        <xs:sequence>
            <xs:element name="evenement" type="Evenement"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Evenement">
        <xs:sequence>
            <xs:element name="dateDebut" type="xs:dateTime"/>
            <xs:element name="dateFin" type="xs:dateTime"/>
            <xs:element name="libelle" type="xs:string"/>    
        </xs:sequence>
        <xs:attribute name="idEvenement" type="xs:int"/>
        <xs:attribute name="idUser" type="xs:int"/>
    </xs:complexType>
    
</xs:schema>

=== Tellenn/ProjetFinalL3/Modules/Calendrier/exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:calendrier
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://www.ujf-grenoble.fr/l3miage/projetjava'
    xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/projetjava file:/home/b/blondelq/Documents/S2/TestProjet/schema.xsd'>
    
    <ns1:evenement idEvenement="1" idUser="1">
        <ns1:dateDebut>2017-04-13T09:00:00</ns1:dateDebut>
        <ns1:dateFin>2017-04-13T11:00:00</ns1:dateFin>
        <ns1:libelle>Reunion</ns1:libelle>
        <ns1:description>Reunion du conseil d'administration de l'entreprise</ns1:description>
    </ns1:evenement>
    
    <ns1:evenement idEvenement="2" idUser="1">
        <ns1:dateDebut>2017-04-14T14:00:00</ns1:dateDebut>
        <ns1:dateFin>2017-04-14T15:00:00</ns1:dateFin>
        <ns1:libelle>Reunion</ns1:libelle>
        <ns1:description>Reunion audit projet KICQA</ns1:description>
    </ns1:evenement>

</ns1:calendrier>
